package:
  name: filelock
  version: "2.0.6"

source:
  fn: filelock-2.0.6.tar.gz
  url: https://files.pythonhosted.org/packages/4f/a2/77c853102454005ff1f95417ae7605b445836212ecd99b717a447c7fb668/filelock-2.0.6.tar.gz
  md5: a4394e1198927d0c24ac172a822faddf
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - filelock = filelock:main
    #
    # Would create an entry point called filelock that calls filelock.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/benediktschmitt/py-filelock
  license: Unlicense
  summary: 'A platform independent file lock.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
